[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core-lib = { path = "../core-lib" }
async-std = "1.12.0"
async-tungstenite = { version="0.25.0", features=["async-native-tls"] }
clap = { version = "4.5.3", features = ["derive"] }
futures = "0.3.30"
