[package]
name = "server"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core-lib = { path = "../core-lib" }
async-std = "1.13.1"
futures = "0.3.31"
futures-util = "0.3.31"
async-tungstenite = { version = "0.30.0", features = ["async-std-runtime"] }
semver = "1.0.26"
clap = { version = "4.5.42", features = ["derive"] }

[dependencies.uuid]
version = "1.17.0"
features = [
    "v4"                # Lets you generate random UUIDs
]