[package]
name = "core-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.0"
rand = "0.8.5"
rng = "0.1.0"
async-std = "1.12.0"
futures = "0.3.30"
